version: "3"

services:
  sapphirenw:
    container_name: mygpt.portlandai.io
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3011:3000
    volumes:
      - .:/mygpt.portlandai.io
